import re
import webbrowser
from datetime import datetime
from pathlib import Path

ARTIFACTS_DIR = Path.home() / "claude_artifacts"


def create_artifact(messages, title="Conversation"):
    ARTIFACTS_DIR.mkdir(exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = re.sub(r"[^\w\s-]", "", title)[:40].strip().replace(" ", "_")
    path = ARTIFACTS_DIR / f"{safe_title}_{ts}.html"
    path.write_text(_render(messages, title), encoding="utf-8")
    webbrowser.open(f"file://{path}")
    return str(path)


def _render(messages, title):
    bodies = []
    for m in messages:
        role = m["role"]
        content = _format_content(m["content"])
        ts = m.get("created_at", "")[:19].replace("T", " ")
        mode = m.get("mode", "")

        if role == "user":
            bodies.append(f"""
        <div class="msg user">
          <div class="msg-meta">You &nbsp;<span class="ts">{ts}</span></div>
          <div class="msg-body">{content}</div>
        </div>""")
        else:
            badge = f'<span class="badge">{mode}</span>' if mode else ""
            bodies.append(f"""
        <div class="msg assistant">
          <div class="msg-meta">Claude {badge} &nbsp;<span class="ts">{ts}</span></div>
          <div class="msg-body">{content}</div>
        </div>""")

    body = "\n".join(bodies)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_esc(title)}</title>
<style>
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
       background:#0d1117;color:#c9d1d9;padding:40px 20px;line-height:1.6}}
  .container{{max-width:820px;margin:0 auto}}
  h1{{color:#e6edf3;font-size:22px;font-weight:600;margin-bottom:24px;
      padding-bottom:12px;border-bottom:1px solid #21262d}}
  .msg{{margin:16px 0;border-radius:10px;padding:16px 20px;border:1px solid #21262d}}
  .user{{background:#1c2128;border-left:3px solid #388bfd}}
  .assistant{{background:#161b22;border-left:3px solid #3fb950}}
  .msg-meta{{font-size:11px;color:#8b949e;margin-bottom:8px;font-weight:600;
             text-transform:uppercase;letter-spacing:.5px}}
  .badge{{background:#1f2937;color:#9ca3af;border-radius:4px;
          padding:1px 6px;font-size:10px;text-transform:none;letter-spacing:0}}
  .ts{{font-weight:400}}
  .msg-body{{white-space:pre-wrap;word-break:break-word;font-size:14px;line-height:1.7}}
  pre{{background:#010409;border:1px solid #30363d;border-radius:6px;
       padding:14px;overflow-x:auto;margin:10px 0}}
  code{{font-family:'JetBrains Mono','Fira Code','Courier New',monospace;font-size:13px;
        color:#e6edf3}}
  p code{{background:#161b22;padding:2px 5px;border-radius:4px;
          border:1px solid #30363d;color:#79c0ff;font-size:13px}}
  .footer{{text-align:center;color:#484f58;font-size:11px;margin-top:48px;padding-top:16px;
            border-top:1px solid #21262d}}
</style>
</head>
<body>
<div class="container">
  <h1>📎 {_esc(title)}</h1>
  {body}
  <div class="footer">Generated by Claude Client &middot; {now}</div>
</div>
</body>
</html>"""


def _esc(t):
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _format_content(text):
    text = _esc(text)
    # Fenced code blocks
    text = re.sub(
        r"```(\w*)\n(.*?)```",
        lambda m: f'<pre><code class="language-{m.group(1)}">{m.group(2)}</code></pre>',
        text,
        flags=re.DOTALL,
    )
    # Inline code
    text = re.sub(r"`([^`\n]+)`", r"<code>\1</code>", text)
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    return text
